---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crdviz
resources:
- resources/namespace.yaml
- resources/service-account.yaml
- resources/rbac.yaml
- resources/deploy.yaml
- resources/service.yaml
images:
- name: ghcr.io/dayzpd/crdviz
  newTag: "2"